$axure.loadCurrentPage({
  "url":"_tour_guide_personal_page.html",
  "generationDate":new Date(1423750819522.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"079b8655b9964ea5b7f7130a8a9b2340",
    "type":"Axure:Page",
    "name":"*Tour Guide Personal Page",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e01364602f244bc898a467cfc75c48a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":595,
              "height":842}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"456990ab68db4efe8911fdb6728dfdb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":595,
                  "height":842}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_tour_guide_personal_page/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "e01364602f244bc898a467cfc75c48a0":{
      "scriptId":"u0"},
    "456990ab68db4efe8911fdb6728dfdb7":{
      "scriptId":"u1"}}});