$axure.loadCurrentPage({
  "url":"_instant_message.html",
  "generationDate":new Date(1423750819964.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"89536859e8a3478fb5b9663ca5f6a462",
    "type":"Axure:Page",
    "name":"*Instant Message",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ee428fb9795a4b0cba93346f43f33c61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":595,
              "height":842}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95fd4daeb6fb4c71a8bff5947d943170",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":595,
                  "height":842}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/message/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "ee428fb9795a4b0cba93346f43f33c61":{
      "scriptId":"u0"},
    "95fd4daeb6fb4c71a8bff5947d943170":{
      "scriptId":"u1"}}});