$axure.loadCurrentPage({
  "url":"hows_transfer_work_.html",
  "generationDate":new Date(1423750819800.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0b9f75b5f01f4db2a222ed8c25b41cf9",
    "type":"Axure:Page",
    "name":"Hows Transfer work?",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"decf8f45b8e941239890aa434ff45ead",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":53},
            "size":{
              "width":306,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47465b82c82a40269a4a38e5c71eae9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":53},
                "size":{
                  "width":306,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "decf8f45b8e941239890aa434ff45ead":{
      "scriptId":"u0"},
    "47465b82c82a40269a4a38e5c71eae9c":{
      "scriptId":"u1"}}});