$axure.loadCurrentPage({
  "url":"_order_detail.html",
  "generationDate":new Date(1423750819926.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2bf6afbf0196469ba93910b930d85749",
    "type":"Axure:Page",
    "name":"*Order detail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f87b3592d40a4c32bcf91312b850cd64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":595,
              "height":842}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c9810b8385f4b9b88d13b682e23d689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":595,
                  "height":842}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/submit_result_-_order/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "f87b3592d40a4c32bcf91312b850cd64":{
      "scriptId":"u0"},
    "4c9810b8385f4b9b88d13b682e23d689":{
      "scriptId":"u1"}}});