$axure.loadCurrentPage({
  "url":"_standard_service.html",
  "generationDate":new Date(1423750819993.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0fb6c3e4e84744e696c782cac45bae19",
    "type":"Axure:Page",
    "name":"*Standard Service",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"32aedd8ebc6e46ecb149a55d884e8f70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":595,
              "height":842}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"514a6b283c9445fa8fbc4efb3cadf296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":595,
                  "height":842}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_standard_service/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "32aedd8ebc6e46ecb149a55d884e8f70":{
      "scriptId":"u0"},
    "514a6b283c9445fa8fbc4efb3cadf296":{
      "scriptId":"u1"}}});