$axure.loadCurrentPage({
  "url":"request.html",
  "generationDate":new Date(1423750819541.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9bc7cf1654f64493a6e659e1c6533d13",
    "type":"Axure:Page",
    "name":"Request",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cf6a5a15871e45d0b74bdca47bbcca85",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":53},
            "size":{
              "width":588,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5361a22fce44dcdb1e6889db5c10bf6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":53},
                "size":{
                  "width":588,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "cf6a5a15871e45d0b74bdca47bbcca85":{
      "scriptId":"u0"},
    "c5361a22fce44dcdb1e6889db5c10bf6":{
      "scriptId":"u1"}}});