$axure.loadCurrentPage({
  "url":"refund___cancellation.html",
  "generationDate":new Date(1423750820175.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"499043bda78b4613839db83da4fb8db3",
    "type":"Axure:Page",
    "name":"Refund & Cancellation",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b5bec6c7b4604a0786f0f36c4667dd0b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":595,
              "height":842}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9925d081ca647119e401c0ff3282799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":595,
                  "height":842}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/company_information/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "b5bec6c7b4604a0786f0f36c4667dd0b":{
      "scriptId":"u0"},
    "a9925d081ca647119e401c0ff3282799":{
      "scriptId":"u1"}}});