$axure.loadCurrentPage({
  "url":"_sign_up___log_in.html",
  "generationDate":new Date(1423750819640.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"53beacbb3fff42b49d4c7dbb37d39ed3",
    "type":"Axure:Page",
    "name":"*Sign Up / Log In",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6b09f3549f2a4a869c1f7f30dec2c8a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":595,
              "height":842}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be9427b3bf742f6a05f6f0a7c63bdf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":595,
                  "height":842}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_sign_up___log_in/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "6b09f3549f2a4a869c1f7f30dec2c8a5":{
      "scriptId":"u0"},
    "4be9427b3bf742f6a05f6f0a7c63bdf9":{
      "scriptId":"u1"}}});