$axure.loadCurrentPage({
  "url":"event_listing_page_.html",
  "generationDate":new Date(1423750820346.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ab06d126aa33418c87e8025dd3355002",
    "type":"Axure:Page",
    "name":"Event Listing page?",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ec5d08b1bb014d5f8f15cc84f39856e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":40},
            "size":{
              "width":559,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df44d639361b4783a57a754128b4ee38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":47,
                  "y":40},
                "size":{
                  "width":559,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ec5d08b1bb014d5f8f15cc84f39856e7":{
      "scriptId":"u0"},
    "df44d639361b4783a57a754128b4ee38":{
      "scriptId":"u1"}}});