$axure.loadCurrentPage({
  "url":"_tour_guide_list.html",
  "generationDate":new Date(1423750819494.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d0ee7ccf2194465ead58deab8efc0049",
    "type":"Axure:Page",
    "name":"*Tour Guide List",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4325bbb40cd84f36838835b2f45b6924",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":595,
              "height":842}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0d2d038597c435e93725da075c1b4a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":595,
                  "height":842}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/_tour_guide_list/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "4325bbb40cd84f36838835b2f45b6924":{
      "scriptId":"u0"},
    "e0d2d038597c435e93725da075c1b4a9":{
      "scriptId":"u1"}}});