$axure.loadCurrentPage({
  "url":"help.html",
  "generationDate":new Date(1423750820144.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e85f4bfc92fb4c4ba9ddaf2b40a6cbe5",
    "type":"Axure:Page",
    "name":"Help",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2b16202984d245249b1057e4288b1d66",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":595,
              "height":842}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dfcb7e20015486f9b1597a5b6f3cfdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":595,
                  "height":842}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/company_information/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "2b16202984d245249b1057e4288b1d66":{
      "scriptId":"u0"},
    "7dfcb7e20015486f9b1597a5b6f3cfdb":{
      "scriptId":"u1"}}});